version: "3"
services:
  employee-jdbc:
    image: employee-jdbc
    ports:
      - "8080:8080"
    networks:
      - employee-mysql
    environment:
      DB_HOST: mysqldb:3306
      DB_USER: vdbuser
      DB_PASSWORD: vdbpass
      DB_NAME: vdbname
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - employee-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: vdbname
      MYSQL_USER: vdbuser
      MYSQL_PASSWORD: vdbpass
      MYSQL_ROOT_PASSWORD: vdbpassroot
    volumes:
     - db_data:/var/lib/mysql  

networks:
  employee-mysql:
